.github/workflows/ci.yml

related to this: https://github.com/FuelLabs/fuel-tx/pull/64

CI run test --all --all-features

---

src/consts.rs
src/lib.rs
src/transaction.rs
src/transaction/id.rs
src/transaction/offset.rs
src/transaction/txio.rs
src/transaction/types.rs
src/transaction/types/storage.rs
src/transaction/validation.rs
src/transaction/validation/error.rs
tests/bytes.rs
tests/offset_cases/factory.rs
tests/valid_cases/transaction.rs

Add fields for storage slot initialization to create txs, as per https://github.com/FuelLabs/fuel-specs/pull/276
closes #74

Storage Slot Initialization

---

.github/workflows/ci.yml
.github/workflows/scripts/verify_tag.sh
Cargo.toml

Release storage slot initialization
also improve speed of tag validation

v0.4.0 Release

---

Cargo.toml

Bump to v0.6.0

---

src/consts.rs

fix: set MAX_{OUTPUTS,INPUTS,WITNESSES} to 255

---

Cargo.toml
test-helpers/Cargo.toml

Bump versions for a new release of fuel-tx

0.8 release

---

src/transaction/validation.rs
src/transaction/validation/error.rs
tests/valid_cases/input.rs

Validate against transactions with duplicate utxo inputs

Validate Duplicate Inputs

---

Cargo.toml

release validation fix for duplicate transaction inputs

0.8.1 patch release

---

Cargo.toml
src/contract.rs
src/lib.rs
src/transaction/offset.rs
src/transaction/txio.rs
src/transaction/types.rs
src/transaction/types/storage.rs

Predicates owner is calculated with the same approach of a contract.
This is part of the validity check of a transaction so this code belongs
to `fuel-tx`.

Add `Contract` code

---

Cargo.toml
src/contract.rs
src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-1.snap
src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-10.snap
src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-100.snap
src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-2.snap
src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-3.snap
src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-4.snap
src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-5.snap
src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-6.snap
src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-7.snap
src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-8.snap
src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-9.snap

Proposal to add additional test coverage for code root calculation to #128

Add test coverage of code root and contract root

---

Cargo.toml

* Feat: Use in memory Merkle trees by @bvrooman in https://github.com/FuelLabs/fuel-tx/pull/156
* remove byte price by @Voxelot in https://github.com/FuelLabs/fuel-tx/pull/157
* @bvrooman made their first contribution in https://github.com/FuelLabs/fuel-tx/pull/156
**Full Changelog**: https://github.com/FuelLabs/fuel-tx/compare/v0.14.0...v0.15.0

Bump to v0.15.0

---

Cargo.toml

- https://github.com/FuelLabs/fuel-tx/pull/155

Release CheckedTransaction 0.15.1

---

.github/workflows/ci.yml
src/checked_transaction.rs
tests/bytes.rs
tests/offset.rs
tests/valid_cases/input.rs
tests/valid_cases/transaction.rs

Related: https://github.com/FuelLabs/fuel-vm/issues/163

Deny clippy warnings and dbg_macro lint

---

Cargo.toml

* Add `TransactionFee` by @vlopes11 in https://github.com/FuelLabs/fuel-tx/pull/160
* Deny clippy warnings and dbg_macro lint by @Dentosal in https://github.com/FuelLabs/fuel-tx/pull/163
* Add precomputed metadata to checked tx by @vlopes11 in https://github.com/FuelLabs/fuel-tx/pull/162
**Full Changelog**: https://github.com/FuelLabs/fuel-tx/compare/v0.15.1...v0.16.0

Bump to v0.16.0

---

Cargo.toml

* Add tx, input, output helper fns by @vlopes11 in https://github.com/FuelLabs/fuel-tx/pull/167
**Full Changelog**: https://github.com/FuelLabs/fuel-tx/compare/v0.16.0...v0.16.1

Bump to v0.16.1

---

src/contract.rs

bind_to_scope isn't working as expected, use different system for insta configuration

fix insta tests

---

src/builder.rs
src/checked_transaction.rs
src/contract.rs
src/lib.rs
src/transaction.rs
src/transaction/id.rs
src/transaction/types.rs
src/transaction/types/input.rs
src/transaction/types/input/consts.rs
src/transaction/types/input/repr.rs
src/transaction/types/output.rs
src/transaction/types/tx_pointer.rs
src/transaction/types/utxo_id.rs
test-helpers/src/lib.rs
tests/bytes.rs
tests/offset.rs
tests/prepared_init.rs
tests/valid_cases/input.rs
tests/valid_cases/output.rs
tests/valid_cases/transaction.rs

related: https://github.com/FuelLabs/fuel-specs/pull/275

Add `TxPointer` to input coin and contract

---

Cargo.toml

Required for https://github.com/FuelLabs/fuel-vm/issues/167

Bump fuel-asm to v0.7

---

src/builder.rs
src/checked_transaction.rs
src/transaction.rs
src/transaction/metadata.rs
src/transaction/offset.rs
src/transaction/types/input.rs
tests/bytes.rs
tests/prepared_init.rs

Change input predicate offset to message & coin

---

Cargo.toml

* Add `TxPointer` to input coin and contract by @vlopes11 in https://github.com/FuelLabs/fuel-tx/pull/170
* Bump fuel-asm to v0.7 by @Dentosal in https://github.com/FuelLabs/fuel-tx/pull/173
* Fix issues with tx init procedures by @Voxelot in https://github.com/FuelLabs/fuel-tx/pull/175
**Full Changelog**: https://github.com/FuelLabs/fuel-tx/compare/v0.16.1...v0.17.0

Bump to v0.17.0

---

src/checked_transaction.rs
src/transaction/fee.rs

Also include unpriced gas info on checked txs, useful for block production to ensure txs don't exceed the block gas limit

add gas info to checked transactions

---

Cargo.toml
src/receipt.rs
src/receipt/receipt_std.rs
src/transaction.rs
tests/bytes.rs

Closes https://github.com/FuelLabs/fuel-tx/issues/194#issue-1391462723

Add contract_id to Receipt::Panic 

---

Cargo.toml

* Refactoring of getters/setters/offset methods of types by @xgreenx in https://github.com/FuelLabs/fuel-tx/pull/197
* Implementation of the `Mint` transaction by @xgreenx in https://github.com/FuelLabs/fuel-tx/pull/202
**Full Changelog**: https://github.com/FuelLabs/fuel-tx/compare/v0.21.0...v0.22.0

Bump version to `0.22.0`
