FuelLabs/fuel-tx

src/transaction.rs, src/transaction/id.rs
Witness data shouldn't be included as part of the transaction id, otherwise signed txs will never match the unsigned version.
closes #62
=> Exclude witness data from transaction id

src/consts.rs
The 16 KiB limit is too low in general, and was also resulting in failing tests etc. due to lack of compiler optimizations (but would be hit eventually anyways even with optimizations).
=> Increase the maximum contract size to 16 MiB.

src/transaction/types/storage.rs
I realized we'll need accessors to retrieve the storage slot fields in downstream crates.
=> add accessors to StorageSlot

src/transaction/id.rs, src/transaction/types/output.rs, tests/bytes.rs, tests/offset_cases/factory.rs, tests/valid_cases/output.rs, tests/valid_cases/transaction.rs
Add the state root field as specified in https://github.com/FuelLabs/fuel-specs/blob/master/specs/protocol/tx_format.md#outputcontractcreated
This was missing from the last release which added initial storage slots to create txs.
=> add state_root field to contract created output

src/receipt/receipt_repr.rs, src/transaction.rs, src/transaction/types/input.rs, src/transaction/types/output.rs
This PR improves the logging for invalid identifiers errors, by specifying where they arrive.
This closes issue #80.
=> feat: improve error logging for invalid identifiers

src/transaction/validation.rs, src/transaction/validation/error.rs
Due to my lack of understanding of variable outputs when initially implementing them, I implemented a validation rule preventing duplicate asset_id's thinking that variable outputs would behave more like change outputs. However, it is perfectly normal for variable outputs to share asset_id's, and they shouldn't be validated from a user input perspective since they're considered to be zeroed out initially.
I'm not removing the error variant from the validation enum yet, as this would create a breaking change to the Rust API and prevent the ability release this fix as a patch.
=> Fix variable output validation rule

.github/workflows/ci.yml, tests/valid_cases/input.rs, tests/valid_cases/transaction.rs
Parallelizing the CI jobs since the tests take so long to run, this is also because we rerun the tests several times with different feature flags enabled.
=> split fuel-tx CI into parallel jobs

src/transaction/validation.rs, src/transaction/validation/error.rs, tests/valid_cases/transaction.rs
Adds several new error types as well as a validation rule for coin outputs.
This is largely to address the tech debt identified here: https://github.com/FuelLabs/fuel-vm/pull/93#pullrequestreview-921424472
=> add new error cases and validation rules

src/lib.rs, src/receipt.rs, src/receipt/receipt_std.rs, src/receipt/script_result.rs, tests/bytes.rs
This PR makes necessary changes in order for the fuel_tx::Receipt type able to reflect the recent spec change of ScriptResult reporting Reverts as a transaction failure.
Replaced usage of InstructionResult for ScriptResult `result` field because:
- InstructionResult includes a panic reason, and it's counter-intuitive to use a type called PanicReason for representing a success. This led to obscure logs for users where they'd see a `PanicReason::RESERV00` which could either mean success or revert.
- While there is a PanicReason::Revert, this would also be misleading since a revert can never cause a panic (unless it was out of gas, but then the panic reason should be OutOfGas, not revert).
- InstructionResult is also incompatible with fully representing a revert. This is because `rA` for a …
=> Receipt Error Improvements

src/consts.rs, src/transaction.rs
Closes #98 
Was reading through fuel-tx as I try to get better understanding of all of fuels packages and crates and figured this may still be worth patching?
I moved them to `consts.rs` to sit with the other public constants, and then adjusted the rest of the package as necessary, but can move them back if needed.
I did also test that they exported correctly locally
=> Make offsets public

src/builder.rs, src/transaction.rs, src/transaction/id.rs, src/transaction/offset.rs, src/transaction/types/input.rs, src/transaction/types/witness.rs, src/transaction/validation.rs, src/transaction/validation/error.rs, test-helpers/Cargo.toml, test-helpers/src/lib.rs, tests/bytes.rs, tests/valid_cases/input.rs, tests/valid_cases/output.rs, tests/valid_cases/transaction.rs
The input coin defined in the specifications is an aggregated type
between two logical variants: signed and predicate.
When the input is expected to behave as coin, the signature validation
should seek its witness counterpart and check the signature with its
fields as arguments = except for predicate and its data.
When the input is expected to behave as predicate, the validation will
check if the owner is the hash of the predicate. The witness id is
entirely ignored.
It is canonical to Rust to split these two different logical structures
into different enum variants - even if we are to maintain the fuel specs
canonical serialization.
Closes #110
=> Split `Input::coin` into predicate and signed

src/builder.rs, src/transaction.rs, src/transaction/id.rs, src/transaction/offset.rs, src/transaction/types/input.rs, src/transaction/types/witness.rs, src/transaction/validation.rs, src/transaction/validation/error.rs, test-helpers/Cargo.toml, test-helpers/src/lib.rs, tests/bytes.rs, tests/valid_cases/input.rs, tests/valid_cases/output.rs, tests/valid_cases/transaction.rs
Reverts FuelLabs/fuel-tx#111
This is major breaking change and we'd like to keep it on a feature branch for now so that we don't block the critical path of releasing the dev net.
=> Revert "Split `Input::coin` into predicate and signed"

src/transaction/validation/error.rs
Make validation errors non-exhaustive so that additional future errors are non-breaking. Typically users only care about whether a validation error occurred or not, and don't attempt to match on every possible variant.
=> Non-Exhaustive Validation Errors

src/builder.rs, src/transaction.rs, src/transaction/internals.rs, src/transaction/txio.rs, src/transaction/validation.rs, tests/valid_cases/transaction.rs
A signed transaction must contain a bytecode length so it won't be
malleable.
Prior to this commit, it checked dynamically; but then the witnesses are
cleared before the tx id computation, so the length is lost.
This commit introduces the attribute that will concretely store the
bytecode len so it will be properly signed and checked.
=> Add bytecode length to tx

src/builder.rs, src/transaction.rs, src/transaction/id.rs, src/transaction/internals.rs, src/transaction/offset.rs, src/transaction/types/input.rs, src/transaction/types/utxo_id.rs, src/transaction/types/witness.rs, src/transaction/validation.rs, src/transaction/validation/error.rs, test-helpers/Cargo.toml, test-helpers/src/lib.rs, tests/bytes.rs, tests/valid_cases/input.rs, tests/valid_cases/output.rs, tests/valid_cases/transaction.rs
The input coin defined in the specifications is an aggregated type
between two logical variants: signed and predicate.
When the input is expected to behave as coin, the signature validation
should seek its witness counterpart and check the signature with its
fields as arguments = except for predicate and its data.
When the input is expected to behave as predicate, the validation will
check if the owner is the hash of the predicate. The witness id is
entirely ignored.
It is canonical to Rust to split these two different logical structures
into different enum variants - even if we are to maintain the fuel specs
canonical serialization.
Closes #110
=> Split `Input::coin` into predicate and signed (#111)

src/consts.rs
Unoptimized contracts use a lot of gas. Bump max gas limit as a temporary measure to alleviate issues.
=> Bump max gas per tx 100x

src/consts.rs, src/lib.rs, src/transaction.rs, src/transaction/consensus_parameters.rs, src/transaction/id.rs, src/transaction/validation.rs, tests/bytes.rs, tests/valid_cases/input.rs, tests/valid_cases/transaction.rs
What?
This PR converts constants used for validating transactions into configurable parameters.
Why?
Making the parameters used for transaction validation compile time constants was overly cumbersome. We're still in the early stages and fine-tuning many of these parameters, so we need to be able to set these validation parameters at runtime rather than requiring new releases of fuel-tx (and docker image of fuel-core) every time a setting is tweaked. Moreover, each fuel-network instantiation may have different requirements.
fixes #114
=> Refactor most constants as configurable parameters

Cargo.toml, src/contract.rs, src/lib.rs, src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-1.snap, src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-10.snap, src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-100.snap, src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-2.snap, src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-3.snap, src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-4.snap, src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-5.snap, src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-6.snap, src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-7.snap, src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-8.snap, src/snapshots/fuel_tx__contract__tests__code_root_snapshot@instructions-9.snap, src/snapshots/fuel_tx__contract__tests__default_state_root_snapshot.snap, src/snapshots/fuel_tx__contract__tests__state_root_snapshot@state-root-0.snap, src/snapshots/fuel_tx__contract__tests__state_root_snapshot@state-root-1.snap, src/transaction.rs, src/transaction/metadata.rs, src/transaction/offset.rs, src/transaction/types/input.rs, src/transaction/validation.rs, tests/bytes.rs, tests/valid_cases/input.rs
A sparse merkle tree is used to calculate the initial state root of a
contract.
It is done so due to the mutable nature of the state.
=> Update contract initial state root to SMT

.github/workflows/ci.yml
this should help the effectiveness of the rust cache in ci since deps wont have to be recompiled with different features everytime a new matrix command runs
=> add cache key to ci

src/transaction/offset.rs, tests/bytes.rs, tests/offset.rs
The receipts root will be updated at runtime in the vm. Hence, its
offset must be known for script transactions.
This function is checking for the correct variant of
`Transaction::Script` so it won't be misused for transactions that
doesn't contain receipts root offsets.
=> Add `Transaction::receipts_root_offset`

src/transaction.rs, src/transaction/consensus_parameters.rs, src/transaction/id.rs, tests/bytes.rs, tests/valid_cases/transaction.rs
The gas price factor will be used to convert between gas units and the
base asset value of the transaction.
This will empower the users to execute cheap/micro transactions without
being punished with high gas overheads.
Related issue: https://github.com/FuelLabs/fuel-specs/issues/342
=> Add gas price factor consensus parameter

Cargo.toml, src/contract.rs, src/transaction/types/input.rs
- Upgrades `fuel-merkle` to 0.3.0
- Replaces regular Merkle trees and storage maps with in-memory Merkle trees
- Uses infallible Merkle tree methods and removes `expect` calls
- Enables `Contract` methods into the no-std context
=> Feat: Use in memory Merkle trees

src/builder.rs, src/consts.rs, src/transaction.rs, src/transaction/consensus_parameters.rs, src/transaction/id.rs, src/transaction/txio.rs, tests/bytes.rs, tests/valid_cases/transaction.rs
fixes: #139 
Remove byte price field as we now have the `GTF` opcode for future proof txs and don't need to pre-emptively include fields we aren't ready for yet.
=> remove byte price

src/consts.rs, src/lib.rs, src/transaction.rs, src/transaction/types.rs, src/transaction/types/input.rs, src/transaction/types/input/consts.rs, src/transaction/types/input/repr.rs, src/transaction/types/output.rs, src/transaction/types/output/consts.rs, src/transaction/types/output/repr.rs, src/transaction/types/utxo_id.rs, tests/offset.rs
The newly introduced instruction `GTF` will set the internal registers
of the interpreter with metadata of the transaction structure.
In order to not leak implementation details of the transaction to the
VM, we need several new helper functions.
=> Add tx, input, output helper fns

src/checked_transaction.rs, src/transaction.rs, src/transaction/types/input.rs, src/transaction/types/output.rs
Remove faulty logic for script init, as the values like stateRoot and balanceRoot are derived from storage/state and not the tx format itself. Furthermore, the utxoid should be unique for each contract input, instead of being set to the currently executing tx.
Updated specs to try to clarify some of this: https://github.com/FuelLabs/fuel-specs/pull/394
=> Fix issues with tx init procedures

Cargo.toml
breaking change since enum fields are public and exhaustive
cc @Salka1988
=> v0.21.0: contract id for panic receipt
